import type { ToolDefinition } from "./types";

const TEXT_LIKE = ["txt", "json", "csv", "xml", "md"];

export const dataTools: ToolDefinition[] = [
  {
    id: "json-formatter",
    slug: "json-formatter",
    href: "/data/json-formatter",
    name: "JSON Formatter & Validator",
    description: "Pretty-print, minify, and validate JSON with clear error messages.",
    category: "data",
    acceptedExtensions: ["json"],
    acceptedMimeTypes: ["application/json"],
    outputExtensions: ["json"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 25,
    keywords: ["json formatter", "json validator", "json minifier", "json beautifier"],
    workflow: "text",
    relatedToolIds: ["json-to-csv", "csv-to-json", "xml-formatter"],
  },
  {
    id: "xml-formatter",
    slug: "xml-formatter",
    href: "/data/xml-formatter",
    name: "XML Formatter",
    description: "Pretty-print or minify XML markup.",
    category: "data",
    acceptedExtensions: ["xml"],
    acceptedMimeTypes: ["application/xml", "text/xml"],
    outputExtensions: ["xml"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 25,
    keywords: ["xml formatter", "xml beautifier", "xml minifier"],
    workflow: "text",
    relatedToolIds: ["json-formatter"],
  },
  {
    id: "csv-to-json",
    slug: "csv-to-json",
    href: "/data/csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV data into a JSON array of objects.",
    category: "data",
    acceptedExtensions: ["csv"],
    acceptedMimeTypes: ["text/csv"],
    outputExtensions: ["json"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 25,
    keywords: ["csv to json", "convert csv"],
    workflow: "text",
    relatedToolIds: ["json-to-csv", "json-formatter"],
  },
  {
    id: "json-to-csv",
    slug: "json-to-csv",
    href: "/data/json-to-csv",
    name: "JSON to CSV",
    description: "Convert a JSON array of objects into CSV rows.",
    category: "data",
    acceptedExtensions: ["json"],
    acceptedMimeTypes: ["application/json"],
    outputExtensions: ["csv"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 25,
    keywords: ["json to csv", "convert json"],
    workflow: "text",
    relatedToolIds: ["csv-to-json", "json-formatter"],
  },
  {
    id: "base64-encode-decode",
    slug: "base64",
    href: "/data/base64",
    name: "Base64 Encode / Decode",
    description: "Encode text to Base64, or decode a Base64 string back to text.",
    category: "data",
    acceptedExtensions: ["txt"],
    acceptedMimeTypes: ["text/plain"],
    outputExtensions: ["txt"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["base64 encode", "base64 decode", "base64 converter"],
    workflow: "text",
    relatedToolIds: ["url-encode-decode", "hash-generator"],
  },
  {
    id: "url-encode-decode",
    slug: "url-encode-decode",
    href: "/data/url-encode-decode",
    name: "URL Encode / Decode",
    description: "Percent-encode text for use in a URL, or decode an encoded URL string.",
    category: "data",
    acceptedExtensions: ["txt"],
    acceptedMimeTypes: ["text/plain"],
    outputExtensions: ["txt"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["url encode", "url decode", "percent encoding"],
    workflow: "text",
    relatedToolIds: ["base64-encode-decode"],
  },
  {
    id: "text-case-converter",
    slug: "case-converter",
    href: "/data/case-converter",
    name: "Text Case Converter",
    description: "Convert text between UPPERCASE, lowercase, Title Case, camelCase, and more.",
    category: "data",
    acceptedExtensions: ["txt"],
    acceptedMimeTypes: ["text/plain"],
    outputExtensions: ["txt"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["case converter", "uppercase", "lowercase", "title case", "camel case"],
    workflow: "text",
    relatedToolIds: ["word-counter"],
  },
  {
    id: "word-counter",
    slug: "word-counter",
    href: "/data/word-counter",
    name: "Word & Character Counter",
    description: "Count words, characters, sentences, and paragraphs, with reading time.",
    category: "data",
    acceptedExtensions: ["txt"],
    acceptedMimeTypes: ["text/plain"],
    outputExtensions: [],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["word counter", "character counter", "text counter"],
    workflow: "text",
    relatedToolIds: ["text-case-converter", "text-diff"],
  },
  {
    id: "uuid-generator",
    slug: "uuid-generator",
    href: "/data/uuid-generator",
    name: "UUID Generator",
    description: "Generate random version-4 UUIDs, one at a time or in bulk.",
    category: "data",
    acceptedExtensions: [],
    acceptedMimeTypes: [],
    outputExtensions: ["txt"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 0,
    keywords: ["uuid generator", "guid generator"],
    workflow: "generator",
    relatedToolIds: ["hash-generator"],
  },
  {
    id: "hash-generator",
    slug: "hash-generator",
    href: "/data/hash-generator",
    name: "Hash Generator",
    description: "Generate SHA-1, SHA-256, SHA-384, or SHA-512 hashes for text or a file.",
    longDescription:
      "Hashes are computed with the browser's native Web Crypto API. These are cryptographic checksums for integrity checks, not a password-hashing or encryption tool.",
    category: "data",
    acceptedExtensions: ["*"],
    acceptedMimeTypes: ["*"],
    outputExtensions: ["txt"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 200,
    keywords: ["sha256", "sha1", "hash generator", "checksum"],
    workflow: "generator",
    relatedToolIds: ["uuid-generator", "base64-encode-decode"],
  },
  {
    id: "text-diff",
    slug: "text-diff",
    href: "/data/text-diff",
    name: "Text Compare / Diff",
    description: "Compare two blocks of text and highlight what changed, line by line.",
    category: "data",
    acceptedExtensions: ["txt"],
    acceptedMimeTypes: ["text/plain"],
    outputExtensions: [],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["text compare", "diff checker", "compare text"],
    workflow: "text",
    relatedToolIds: ["word-counter"],
  },
  {
    id: "markdown-to-html",
    slug: "markdown-to-html",
    href: "/document/markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown into clean, styled HTML you can preview and download.",
    category: "document",
    acceptedExtensions: ["md"],
    acceptedMimeTypes: ["text/markdown"],
    outputExtensions: ["html"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["markdown to html", "md to html"],
    workflow: "text",
    relatedToolIds: ["markdown-to-pdf", "txt-to-html"],
  },
  {
    id: "markdown-to-pdf",
    slug: "markdown-to-pdf",
    href: "/document/markdown-to-pdf",
    name: "Markdown to PDF",
    description: "Turn a Markdown document into a formatted PDF, headings and all.",
    category: "document",
    acceptedExtensions: ["md"],
    acceptedMimeTypes: ["text/markdown"],
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["markdown to pdf", "md to pdf"],
    workflow: "text",
    relatedToolIds: ["markdown-to-html", "txt-to-pdf"],
  },
  {
    id: "txt-to-pdf",
    slug: "txt-to-pdf",
    href: "/document/txt-to-pdf",
    name: "TXT to PDF",
    description: "Convert a plain text file into a paginated PDF document.",
    category: "document",
    acceptedExtensions: TEXT_LIKE,
    acceptedMimeTypes: ["text/plain"],
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["txt to pdf", "text to pdf"],
    workflow: "text",
    relatedToolIds: ["markdown-to-pdf", "txt-to-html"],
  },
  {
    id: "txt-to-html",
    slug: "txt-to-html",
    href: "/document/txt-to-html",
    name: "TXT to HTML",
    description: "Wrap plain text into a minimal, valid HTML document.",
    category: "document",
    acceptedExtensions: TEXT_LIKE,
    acceptedMimeTypes: ["text/plain"],
    outputExtensions: ["html"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 10,
    keywords: ["txt to html", "text to html"],
    workflow: "text",
    relatedToolIds: ["markdown-to-html", "txt-to-pdf"],
  },
];

export const archiveTools: ToolDefinition[] = [
  {
    id: "zip-create",
    slug: "zip",
    href: "/archive/zip",
    name: "Create ZIP Archive",
    description: "Bundle multiple files into a single ZIP archive.",
    category: "archive",
    acceptedExtensions: ["*"],
    acceptedMimeTypes: ["*"],
    outputExtensions: ["zip"],
    processingMode: "local",
    status: "available",
    supportsMultiple: true,
    maxRecommendedSizeMb: 300,
    keywords: ["create zip", "zip files", "compress files"],
    workflow: "file",
    relatedToolIds: ["zip-extract"],
  },
  {
    id: "zip-extract",
    slug: "unzip",
    href: "/archive/unzip",
    name: "Extract ZIP Archive",
    description: "Inspect a ZIP archive's contents and extract its files.",
    category: "archive",
    acceptedExtensions: ["zip"],
    acceptedMimeTypes: ["application/zip", "application/x-zip-compressed"],
    outputExtensions: ["*"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 300,
    keywords: ["unzip", "extract zip", "open zip file"],
    workflow: "file",
    relatedToolIds: ["zip-create"],
  },
];
