import type { ToolDefinition } from "./types";

const PDF_MIME = ["application/pdf"];
const PDF_EXT = ["pdf"];

export const pdfTools: ToolDefinition[] = [
  {
    id: "pdf-merge",
    slug: "merge",
    href: "/pdf/merge",
    name: "Merge PDF",
    shortName: "Merge",
    description: "Combine multiple PDF files into a single document, in the order you choose.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: true,
    maxRecommendedSizeMb: 150,
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf joiner"],
    workflow: "file",
    relatedToolIds: ["pdf-split", "pdf-reorder", "pdf-compress"],
    faq: [
      {
        question: "Is there a limit on how many PDFs I can merge?",
        answer: "No hard limit, but very large or numerous files are processed in your browser's memory, so extremely large batches may be slow on low-memory devices.",
      },
      {
        question: "Does merging change the page order?",
        answer: "Pages are combined in the order you arrange the files before merging.",
      },
    ],
  },
  {
    id: "pdf-split",
    slug: "split",
    href: "/pdf/split",
    name: "Split PDF",
    description: "Split a PDF into multiple files, a fixed number of pages at a time.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf", "zip"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["split pdf", "separate pdf pages", "pdf splitter"],
    workflow: "file",
    relatedToolIds: ["pdf-merge", "pdf-extract-pages", "pdf-delete-pages"],
  },
  {
    id: "pdf-extract-pages",
    slug: "extract-pages",
    href: "/pdf/extract-pages",
    name: "Extract PDF Pages",
    description: "Pull specific pages out of a PDF into a brand-new document.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["extract pdf pages", "get pages from pdf", "pdf page extractor"],
    workflow: "file",
    relatedToolIds: ["pdf-delete-pages", "pdf-split", "pdf-merge"],
  },
  {
    id: "pdf-delete-pages",
    slug: "delete-pages",
    href: "/pdf/delete-pages",
    name: "Delete PDF Pages",
    description: "Remove one or more pages from a PDF and download the result.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["delete pdf pages", "remove pdf pages"],
    workflow: "file",
    relatedToolIds: ["pdf-extract-pages", "pdf-reorder", "pdf-merge"],
  },
  {
    id: "pdf-rotate",
    slug: "rotate",
    href: "/pdf/rotate",
    name: "Rotate PDF",
    description: "Rotate every page, or a specific selection of pages, in a PDF.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["rotate pdf", "turn pdf pages"],
    workflow: "file",
    relatedToolIds: ["pdf-reorder", "pdf-delete-pages"],
  },
  {
    id: "pdf-reorder",
    slug: "reorder",
    href: "/pdf/reorder",
    name: "Reorder PDF Pages",
    description: "Drag pages into a new order and export the rearranged PDF.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["reorder pdf pages", "rearrange pdf", "sort pdf pages"],
    workflow: "file",
    relatedToolIds: ["pdf-rotate", "pdf-delete-pages"],
  },
  {
    id: "images-to-pdf",
    slug: "images-to-pdf",
    href: "/pdf/images-to-pdf",
    name: "Images to PDF",
    description: "Combine JPG and PNG images into a single PDF document.",
    category: "pdf",
    acceptedExtensions: ["jpg", "jpeg", "png"],
    acceptedMimeTypes: ["image/jpeg", "image/png"],
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: true,
    maxRecommendedSizeMb: 150,
    keywords: ["jpg to pdf", "png to pdf", "images to pdf", "photo to pdf"],
    workflow: "file",
    relatedToolIds: ["pdf-to-images", "pdf-merge"],
  },
  {
    id: "pdf-to-images",
    slug: "to-images",
    href: "/pdf/to-images",
    name: "PDF to Images",
    description: "Export each page of a PDF as a PNG or JPG image.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["png", "jpg", "zip"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 100,
    keywords: ["pdf to jpg", "pdf to png", "pdf to image"],
    workflow: "file",
    relatedToolIds: ["images-to-pdf", "pdf-compress"],
  },
  {
    id: "pdf-add-page-numbers",
    slug: "page-numbers",
    href: "/pdf/page-numbers",
    name: "Add Page Numbers to PDF",
    description: "Stamp page numbers onto every page of a PDF, with your choice of position.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["add page numbers to pdf", "number pdf pages"],
    workflow: "file",
    relatedToolIds: ["pdf-watermark", "pdf-metadata"],
  },
  {
    id: "pdf-watermark",
    slug: "watermark",
    href: "/pdf/watermark",
    name: "Add Watermark to PDF",
    description: "Overlay a custom text watermark across every page of a PDF.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["watermark pdf", "add text to pdf"],
    workflow: "file",
    relatedToolIds: ["pdf-add-page-numbers", "pdf-metadata"],
  },
  {
    id: "pdf-metadata",
    slug: "metadata",
    href: "/pdf/metadata",
    name: "PDF Metadata Viewer & Remover",
    description: "View a PDF's title, author, and other metadata, and strip it out if you want.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["pdf metadata", "remove pdf metadata", "pdf properties"],
    workflow: "file",
    relatedToolIds: ["pdf-compress", "pdf-watermark"],
  },
  {
    id: "pdf-compress",
    slug: "compress",
    href: "/pdf/compress",
    name: "Compress PDF",
    description: "Losslessly re-save a PDF with optimized internal structure. Best on text-heavy PDFs; won't shrink ones dominated by embedded images.",
    longDescription:
      "This tool re-encodes the PDF's internal object structure using compressed cross-reference streams — it never re-samples or degrades embedded images, so it's completely safe. That safety has a real limit worth knowing: on PDFs whose size is mostly one or two large embedded photos or scans, this typically saves close to nothing, because the image data itself isn't touched. It helps most on PDFs with a lot of internal structure — many pages, fonts, form fields, or annotations — and little to no embedded imagery. If your PDF doesn't shrink, that's expected for that file, not a bug.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf"],
    workflow: "file",
    relatedToolIds: ["pdf-metadata", "pdf-to-images"],
    faq: [
      {
        question: "Why didn't my PDF get any smaller?",
        answer:
          "If your PDF is mostly one or more large embedded images (a scan, a photo-heavy document), this is expected. This tool optimizes the PDF's internal structure without ever re-compressing embedded images, so files where images dominate the size won't shrink much, if at all. It works best on PDFs with a lot of pages, fonts, or form fields and relatively little embedded imagery.",
      },
      {
        question: "Is this the same as the image compression other PDF tools offer?",
        answer:
          "No. Some PDF compressors re-sample embedded images at lower resolution or quality to shrink file size, which can visibly degrade photos and scans. This tool never does that — it only touches the document's internal structure, so the visual result is identical to the original.",
      },
    ],
  },
];
