import type { ToolDefinition } from "./types";

const PDF_MIME = ["application/pdf"];
const PDF_EXT = ["pdf"];

export const pdfTools: ToolDefinition[] = [
  {
    id: "pdf-editor",
    slug: "editor",
    href: "/pdf/editor",
    name: "PDF Editor",
    shortName: "Editor",
    description: "Edit text, annotate, sign, organize and OCR PDFs directly in your browser.",
    longDescription:
      "A full editing workspace for PDFs: correct short text on normal pages, recognize and correct text on scanned pages using the same local OCR engine as the standalone OCR tool, add text/images/signatures, highlight and draw, cover content, and reorganize pages — all processed on your device. Best for short text corrections, annotations, and page organization, not full document authoring: complex formatting, embedded fonts, and paragraph reflow may not be preserved exactly.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "experimental",
    supportsMultiple: false,
    maxRecommendedSizeMb: 60,
    keywords: [
      "edit pdf",
      "pdf editor",
      "add text to pdf",
      "sign pdf",
      "annotate pdf",
      "edit scanned pdf",
      "pdf text editor",
    ],
    workflow: "file",
    relatedToolIds: ["pdf-ocr", "pdf-merge", "pdf-watermark", "pdf-add-page-numbers"],
    faq: [
      {
        question: "Can this replace Adobe Acrobat for editing PDFs?",
        answer:
          "No — this is best for short text corrections, annotations, signatures, and page organization. It doesn't reflow paragraphs, reconstruct complex layouts, or preserve embedded fonts exactly. For heavy document authoring, a desktop editor is still the better tool.",
      },
      {
        question: "How does editing scanned pages work?",
        answer:
          "The editor reuses the same local OCR engine as the standalone OCR PDF tool. Recognize a scanned page, then click any recognized word or line to correct it — the correction covers the original scanned text and places the new text (and an updated searchable layer) at the same position.",
      },
      {
        question: "Does correcting text remove the original from the file?",
        answer:
          "No. Corrections are drawn over the original content, not removed from it — this is the same practical approach every browser-based PDF editor uses, since true in-place PDF text mutation isn't reliable. The original is visually covered, and for scanned pages the searchable text is updated to the corrected value.",
      },
      {
        question: "Is the Whiteout tool a secure way to redact sensitive information?",
        answer:
          "No. Whiteout visually covers content — it does not remove the underlying data from the PDF file. Don't use it for legally or security-sensitive redaction.",
      },
    ],
  },
  {
    id: "pdf-merge",
    slug: "merge",
    href: "/pdf/merge",
    name: "Merge PDF",
    shortName: "Merge",
    description: "Combine multiple PDF files into a single document, in the order you choose.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: true,
    maxRecommendedSizeMb: 150,
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf joiner"],
    workflow: "file",
    relatedToolIds: ["pdf-split", "pdf-reorder", "pdf-compress"],
    faq: [
      {
        question: "Is there a limit on how many PDFs I can merge?",
        answer: "No hard limit, but very large or numerous files are processed in your browser's memory, so extremely large batches may be slow on low-memory devices.",
      },
      {
        question: "Does merging change the page order?",
        answer: "Pages are combined in the order you arrange the files before merging.",
      },
    ],
  },
  {
    id: "pdf-split",
    slug: "split",
    href: "/pdf/split",
    name: "Split PDF",
    description: "Split a PDF into multiple files, a fixed number of pages at a time.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf", "zip"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["split pdf", "separate pdf pages", "pdf splitter"],
    workflow: "file",
    relatedToolIds: ["pdf-merge", "pdf-extract-pages", "pdf-delete-pages"],
  },
  {
    id: "pdf-extract-pages",
    slug: "extract-pages",
    href: "/pdf/extract-pages",
    name: "Extract PDF Pages",
    description: "Pull specific pages out of a PDF into a brand-new document.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["extract pdf pages", "get pages from pdf", "pdf page extractor"],
    workflow: "file",
    relatedToolIds: ["pdf-delete-pages", "pdf-split", "pdf-merge"],
  },
  {
    id: "pdf-delete-pages",
    slug: "delete-pages",
    href: "/pdf/delete-pages",
    name: "Delete PDF Pages",
    description: "Remove one or more pages from a PDF and download the result.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["delete pdf pages", "remove pdf pages"],
    workflow: "file",
    relatedToolIds: ["pdf-extract-pages", "pdf-reorder", "pdf-merge"],
  },
  {
    id: "pdf-rotate",
    slug: "rotate",
    href: "/pdf/rotate",
    name: "Rotate PDF",
    description: "Rotate every page, or a specific selection of pages, in a PDF.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["rotate pdf", "turn pdf pages"],
    workflow: "file",
    relatedToolIds: ["pdf-reorder", "pdf-delete-pages"],
  },
  {
    id: "pdf-reorder",
    slug: "reorder",
    href: "/pdf/reorder",
    name: "Reorder PDF Pages",
    description: "Drag pages into a new order and export the rearranged PDF.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["reorder pdf pages", "rearrange pdf", "sort pdf pages"],
    workflow: "file",
    relatedToolIds: ["pdf-rotate", "pdf-delete-pages"],
  },
  {
    id: "images-to-pdf",
    slug: "images-to-pdf",
    href: "/pdf/images-to-pdf",
    name: "Images to PDF",
    description: "Combine JPG and PNG images into a single PDF document.",
    category: "pdf",
    acceptedExtensions: ["jpg", "jpeg", "png"],
    acceptedMimeTypes: ["image/jpeg", "image/png"],
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: true,
    maxRecommendedSizeMb: 150,
    keywords: ["jpg to pdf", "png to pdf", "images to pdf", "photo to pdf"],
    workflow: "file",
    relatedToolIds: ["pdf-to-images", "pdf-merge", "pdf-ocr"],
  },
  {
    id: "pdf-to-images",
    slug: "to-images",
    href: "/pdf/to-images",
    name: "PDF to Images",
    description: "Export each page of a PDF as a PNG or JPG image.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["png", "jpg", "zip"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 100,
    keywords: ["pdf to jpg", "pdf to png", "pdf to image"],
    workflow: "file",
    relatedToolIds: ["images-to-pdf", "pdf-compress", "pdf-ocr"],
  },
  {
    id: "pdf-add-page-numbers",
    slug: "page-numbers",
    href: "/pdf/page-numbers",
    name: "Add Page Numbers to PDF",
    description: "Stamp page numbers onto every page of a PDF, with your choice of position.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["add page numbers to pdf", "number pdf pages"],
    workflow: "file",
    relatedToolIds: ["pdf-watermark", "pdf-metadata"],
  },
  {
    id: "pdf-watermark",
    slug: "watermark",
    href: "/pdf/watermark",
    name: "Add Watermark to PDF",
    description: "Overlay a custom text watermark across every page of a PDF.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["watermark pdf", "add text to pdf"],
    workflow: "file",
    relatedToolIds: ["pdf-add-page-numbers", "pdf-metadata"],
  },
  {
    id: "pdf-metadata",
    slug: "metadata",
    href: "/pdf/metadata",
    name: "PDF Metadata Viewer & Remover",
    description: "View a PDF's title, author, and other metadata, and strip it out if you want.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["pdf metadata", "remove pdf metadata", "pdf properties"],
    workflow: "file",
    relatedToolIds: ["pdf-compress", "pdf-watermark"],
  },
  {
    id: "pdf-compress",
    slug: "compress",
    href: "/pdf/compress",
    name: "Compress PDF",
    description: "Shrink a PDF by merging repeated images and tidying its structure — or, if you choose, re-saving its photos and scans at lower quality. Tells you what to expect before you start.",
    longDescription:
      "Compress PDF works in two ways, and it shows you which one can help your file before you press anything. Lossless (the default) never changes how a page looks: it merges images that are embedded more than once and rewrites the file structure more compactly. That helps files with many pages, fonts, or repeated images, but a PDF that is mostly scanned pages or photos will barely shrink this way. For those, Balanced and Smallest re-save the embedded JPEG images at lower quality (and fewer pixels if they are larger than needed) — a real, visible trade-off that you opt into. The result screen reports the true before and after sizes; if a file cannot get smaller it says so instead of pretending.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf"],
    processingMode: "local",
    status: "available",
    supportsMultiple: false,
    maxRecommendedSizeMb: 150,
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf"],
    workflow: "file",
    relatedToolIds: ["pdf-metadata", "pdf-to-images"],
    faq: [
      {
        question: "Why didn't my PDF get any smaller?",
        answer:
          "Lossless mode only merges repeated images and tidies the file structure, so a PDF made of scanned pages or photos barely changes. Choose Balanced or Smallest to re-save those images at lower quality — that is the only way to shrink such a file. A PDF that is mostly text is usually already close to its minimum size.",
      },
      {
        question: "Does compressing reduce quality?",
        answer:
          "Only if you choose Balanced or Smallest, and the page tells you exactly what changes: image JPEG quality (about 72% or 50%) and a cap on image resolution (2000 px or 1400 px on the long side). Text and vector graphics are never touched. Lossless leaves every page visually identical.",
      },
      {
        question: "What kinds of images can it recompress?",
        answer:
          "JPEG images embedded in the PDF (which is what scanners and cameras normally produce). Other image encodings are left exactly as they are, and the analysis shown after you upload tells you how many images are affected.",
      },
    ],
  },
  {
    id: "pdf-ocr",
    slug: "ocr",
    href: "/pdf/ocr",
    name: "OCR PDF",
    shortName: "OCR",
    description: "Turn scanned PDFs into searchable PDFs directly in your browser.",
    longDescription:
      "This tool recognizes text on scanned or image-only PDF pages using Tesseract.js, a local, open-source (Apache-2.0) OCR engine — nothing is uploaded. It works best for correcting or extracting individual words, values, and short text; complex formatting, tables, and handwriting may not be recognized accurately. See the tool status page for verified languages.",
    category: "pdf",
    acceptedExtensions: PDF_EXT,
    acceptedMimeTypes: PDF_MIME,
    outputExtensions: ["pdf", "txt"],
    processingMode: "local",
    status: "experimental",
    supportsMultiple: false,
    maxRecommendedSizeMb: 60,
    keywords: ["ocr pdf", "scanned pdf to text", "searchable pdf", "image pdf to text", "recognize text in pdf"],
    workflow: "file",
    relatedToolIds: ["pdf-editor", "pdf-to-images", "images-to-pdf", "pdf-compress"],
    faq: [
      {
        question: "Does my document get uploaded anywhere?",
        answer:
          "No. The PDF, the rendered page images, and the recognized text all stay on your device. Your browser does download the OCR engine and language model the first time you use this tool (a few megabytes, served from thefileconvert.com, not a third party) — never your document.",
      },
      {
        question: "How accurate is the OCR?",
        answer:
          "It works well on clean, typed, well-scanned pages in a supported language. Accuracy drops on low-resolution scans, poor contrast, unusual fonts, and handwriting. Numbers, dates, and currency are usually recognized reliably on clean scans — always double-check anything important.",
      },
      {
        question: "Can I edit the recognized text in place on the scan?",
        answer:
          "Not yet — this V1 focuses on making scanned PDFs searchable and extracting their text. In-place correction of individual recognized words on the page is planned for a future PDF editor.",
      },
    ],
  },
];
