import type { ToolDefinition } from "./types";

/**
 * Tools that are on the roadmap but require infrastructure (a server, a
 * heavy runtime, or a licensed engine) we don't want to fake in V1. They
 * are listed on the tool status page as "Coming soon" and are never
 * reachable as working routes, so marketing never gets ahead of reality.
 */
export const roadmapTools: ToolDefinition[] = [
  {
    id: "pdf-protect",
    slug: "protect",
    href: "/pdf/protect",
    name: "Protect PDF (Add Password)",
    description: "Encrypt a PDF with a password.",
    category: "pdf",
    acceptedExtensions: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputExtensions: ["pdf"],
    processingMode: "server-assisted",
    status: "coming-soon",
    supportsMultiple: false,
    maxRecommendedSizeMb: 0,
    keywords: ["protect pdf", "password protect pdf", "encrypt pdf"],
    workflow: "file",
  },
  {
    id: "pdf-unlock",
    slug: "unlock",
    href: "/pdf/unlock",
    name: "Unlock PDF (Remove Password)",
    description: "Remove a known password from a PDF.",
    category: "pdf",
    acceptedExtensions: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputExtensions: ["pdf"],
    processingMode: "server-assisted",
    status: "coming-soon",
    supportsMultiple: false,
    maxRecommendedSizeMb: 0,
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf"],
    workflow: "file",
  },
  {
    id: "docx-to-pdf",
    slug: "docx-to-pdf",
    href: "/document/docx-to-pdf",
    name: "DOCX to PDF",
    description: "Convert a Word document to PDF.",
    category: "document",
    acceptedExtensions: ["docx"],
    acceptedMimeTypes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    outputExtensions: ["pdf"],
    processingMode: "server-assisted",
    status: "coming-soon",
    supportsMultiple: false,
    maxRecommendedSizeMb: 0,
    keywords: ["docx to pdf", "word to pdf"],
    workflow: "file",
  },
  {
    id: "pdf-to-docx",
    slug: "pdf-to-docx",
    href: "/pdf/to-docx",
    name: "PDF to DOCX",
    description: "Convert a PDF into an editable Word document.",
    category: "document",
    acceptedExtensions: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputExtensions: ["docx"],
    processingMode: "server-assisted",
    status: "coming-soon",
    supportsMultiple: false,
    maxRecommendedSizeMb: 0,
    keywords: ["pdf to word", "pdf to docx"],
    workflow: "file",
  },
  {
    id: "video-to-audio",
    slug: "video-to-audio",
    href: "/media/video-to-audio",
    name: "Video to Audio (MP4 to MP3)",
    description: "Extract the audio track from a video file.",
    category: "media",
    acceptedExtensions: ["mp4"],
    acceptedMimeTypes: ["video/mp4"],
    outputExtensions: ["mp3"],
    processingMode: "server-assisted",
    status: "coming-soon",
    supportsMultiple: false,
    maxRecommendedSizeMb: 0,
    keywords: ["mp4 to mp3", "video to audio", "extract audio"],
    workflow: "file",
  },
  {
    id: "media-trim",
    slug: "trim",
    href: "/media/trim",
    name: "Trim Audio or Video",
    description: "Cut a clip from an audio or video file.",
    category: "media",
    acceptedExtensions: ["mp4", "mp3"],
    acceptedMimeTypes: ["video/mp4", "audio/mpeg"],
    outputExtensions: ["mp4", "mp3"],
    processingMode: "server-assisted",
    status: "coming-soon",
    supportsMultiple: false,
    maxRecommendedSizeMb: 0,
    keywords: ["trim video", "trim audio", "cut video clip"],
    workflow: "file",
  },
];
